### ISSUE TITLE
Icons show to small

### ISSUE THREAD

**Issue by sjikkervisje** [mampfes/ha-knx-uf-iconset#2]
All these icons show to small in Home Assistant compared to the native MDI Icon set. Looking at the icons on the forum there is allot of empty space around them which causes this.

Is there a way to adjust this package so it accounts for that and shows the icon large enough?

**Comment by mampfes** [comment]
Hi, the icons provide much more details than the MDI icons - therefore they definitely need more space. Otherwise the SVG renderer will blur them if there are not enough pixels.

Currently there is no option to remove extra space. However I'm not sure if there is still extra space around the icons - the standard Lovelace cards render all icons very small. But I will check.

I use button-cards to show bigger icons.

**Comment by nagyrobi** [comment]
If you change the `viewBox` to something like `"50 50 260 260"` a whole lot of space will be reclaimed.

**Comment by mampfes** [comment]
fixed in release 1.1.0
